In [11]:
import numpy as np
from numpy.random import rand

In [12]:
x=np.array(([9,8],[6,3],[9,1],[9,8])) #features

In [13]:
x

array([[9, 8],
       [6, 3],
       [9, 1],
       [9, 8]])

In [14]:
y=np.array([[0],[1],[1],[0]]) #labels

In [15]:
y

array([[0],
       [1],
       [1],
       [0]])

In [16]:
def sigmoid(z) :
    return 1/(1+np.exp(-z))
    

In [122]:
class Neaurnetwork:
    def __init__(self,x,y,nodes_in_layer1=4,nodes_in_layer2=3,nodes_in_layer3=1,l_rate=1):
        #define x,y
        self.input_in_layer0 = x
        self.y=y
        self.l_rate=l_rate
        
        #number of neurons in layer
        self.nodes_in_layer1=nodes_in_layer1
        self.nodes_in_layer2=nodes_in_layer2
        self.nodes_in_layer3=nodes_in_layer3
        
        #set the weights (theta) metrics
        self.theta_layer0=np.random.rand(self.input_in_layer0.shape[1]+1,self.nodes_in_layer1)
        self.theta_layer1=np.random.rand(self.nodes_in_layer1+1,self.nodes_in_layer2)
        self.theta_layer2=np.random.rand(self.nodes_in_layer2+1,self.nodes_in_layer3)
  

        
    def feedforward(self):
        #compute all nodes (a1,a2,a3,a4) in layer 1
        self.z1=self.theta_layer0[0]+np.dot(self.input_in_layer0,self.theta_layer0[1:])
        self.layer1=sigmoid(self.z1)
        
         #compute all nodes (a1,a2,a3) in layer 2
        self.z2=self.theta_layer1[0]+np.dot(self.layer1,self.theta_layer1[1:])
        self.layer2=sigmoid(self.z2)
        
         #compute all nodes (a1,a2,a3) in layer 1
        self.z3=self.theta_layer2[0]+np.dot(self.layer2,self.theta_layer2[1:])
        self.layer3=sigmoid(self.z3)
        
        return self.layer3
    
    ### cost function
    
    def cost_fun(self):
        self.n=self.input_in_layer0.shape[0] #number of training example
        self.cost=(1/self.n)*np.sum(-self.y *np.log(self.layer3)-(1-self.y)*np.log(1-self.layer3))#cross entropy
        return self.cost
    
    ### back propgation
    def backpropgation(self):
        
        ## dervation of E with respect to theta and bias in layer2
        self.dE_layer3 =(1/self.n)*(self.layer3-y)/(self.layer3*(1-self.layer3))
        self.dE_dz3 =np.multiply(self.dE_layer3,sigmoid(self.z3)*(1-sigmoid(self.z3)))
        self.dE_dtheta2=np.dot(self.layer2.T, self.dE_dz3)
        self.dbias2=np.dot(np.ones(self.n), self.dE_dz3)
        
        ## dervation of E with respect to theta and bias in layer1
        self.dE_layer2 =np.dot(self.dE_dz3,self.theta_layer2[1:].T)
        self.dE_dz2 =np.multiply(self.dE_layer2,sigmoid(self.z2)*(1-sigmoid(self.z2)))
        self.dE_dtheta1=np.dot(self.layer1.T, self.dE_dz2)
        self.dbias1=np.dot(np.ones(self.n), self.dE_dz2)
        
        
        ## dervation of E with respect to theta and bias in layer0
        self.dE_layer1 =np.dot(self.dE_dz2,self.theta_layer1[1:].T)
        self.dE_dz1 =np.multiply(self.dE_layer1,sigmoid(self.z1)*(1-sigmoid(self.z1)))
        self.dE_dtheta0=np.dot(self.input_in_layer0.T, self.dE_dz1)
        self.dbias0=np.dot(np.ones(self.n), self.dE_dz1)
        
        ## updating theta using gradient descent in layer 2,1 and 0
        self.theta_layer2[1:] = self.theta_layer2[1:]- self.l_rate * self.dE_dtheta2
        self.theta_layer1[1:] = self.theta_layer1[1:]- self.l_rate * self.dE_dtheta1
        self.theta_layer0[1:] = self.theta_layer0[1:]- self.l_rate * self.dE_dtheta0
        
        
        
        ## updating bias using gradient descent in layer 2,1 and 0
        self.theta_layer2[0] = self.theta_layer2[0] - self.l_rate * np.sum(self.dE_dz3, axis=0)
        self.theta_layer1[0] = self.theta_layer1[0] - self.l_rate * np.sum(self.dE_dz2, axis=0)
        self.theta_layer0[0] = self.theta_layer0[0] - self.l_rate * np.sum(self.dE_dz1, axis=0)
        
        
        return self
        
        
        

In [123]:

NN=Neaurnetwork(x,y)

### feed forward

In [124]:
predict=NN.feedforward()

In [125]:
print('actual output :\n ',y)

actual output :
  [[0]
 [1]
 [1]
 [0]]


In [126]:
print('prediction output :\n ',predict)

prediction output :
  [[0.88768016]
 [0.88755516]
 [0.88752994]
 [0.88768016]]



### back propgation

In [127]:
epochs=1000
losses=[]
for i in range(epochs):
    prediction_output=NN.feedforward()
    error=NN.cost_fun()
    losses.append(error)
    u=NN.backpropgation()
    print('iteration ::> ',i+1)
    print('actual output :\n ',y)
    print('prediction output :\n ',prediction_output,'\n')
    print('cost : \n',error,'\n')
    

iteration ::>  1
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.88768016]
 [0.88755516]
 [0.88752994]
 [0.88768016]] 

cost : 
 1.152851774543336 

iteration ::>  2
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.66853108]
 [0.6685068 ]
 [0.6685001 ]
 [0.66853108]] 

cost : 
 0.7534674697678752 

iteration ::>  3
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.52741654]
 [0.52751603]
 [0.52753306]
 [0.52741654]] 

cost : 
 0.6945504011296149 

iteration ::>  4
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.5031185 ]
 [0.50324019]
 [0.50326178]
 [0.5031185 ]] 

cost : 
 0.6930349851294583 

iteration ::>  5
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.50011267]
 [0.50023813]
 [0.5002608 ]
 [0.50011267]] 

cost : 
 0.6930104599025949 

iteration ::>  6
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.49974361]
 [0.4998706 ]
 [0.49989394]
 [0.49974361]] 

cost : 
 0.6930086000201969 


iteration ::>  76
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.49921648]
 [0.49956927]
 [0.49978519]
 [0.49921648]] 

cost : 
 0.6926871626203437 

iteration ::>  77
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.49919777]
 [0.49955916]
 [0.49978485]
 [0.49919777]] 

cost : 
 0.6926737133205791 

iteration ::>  78
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.49917817]
 [0.49954856]
 [0.49978461]
 [0.49917817]] 

cost : 
 0.6926595654352175 

iteration ::>  79
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.49915762]
 [0.49953744]
 [0.4997845 ]
 [0.49915762]] 

cost : 
 0.6926446687541464 

iteration ::>  80
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.49913605]
 [0.49952575]
 [0.49978454]
 [0.49913605]] 

cost : 
 0.6926289686608564 

iteration ::>  81
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.49911339]
 [0.49951346]
 [0.49978473]
 [0.49911339]] 

cost : 
 0.69261240570

iteration ::>  269
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.04057256]
 [0.93848204]
 [0.94848031]
 [0.04057256]] 

cost : 
 0.049805749241989425 

iteration ::>  270
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.03982171]
 [0.93960151]
 [0.94941216]
 [0.03982171]] 

cost : 
 0.048871069262826236 

iteration ::>  271
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.0390951 ]
 [0.94068699]
 [0.95031578]
 [0.0390951 ]] 

cost : 
 0.04796636068390467 

iteration ::>  272
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.03839163]
 [0.94173984]
 [0.95119229]
 [0.03839163]] 

cost : 
 0.04709031817455687 

iteration ::>  273
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.03771029]
 [0.94276137]
 [0.95204279]
 [0.03771029]] 

cost : 
 0.04624170618028216 

iteration ::>  274
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.03705011]
 [0.94375281]
 [0.95286828]
 [0.03705011]] 

cost : 
 

iteration ::>  570
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.00496526]
 [0.99269141]
 [0.9937576 ]
 [0.00496526]] 

cost : 
 0.005888164963253635 

iteration ::>  571
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.00494944]
 [0.99271512]
 [0.99377761]
 [0.00494944]] 

cost : 
 0.005869210143688258 

iteration ::>  572
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.00493372]
 [0.99273868]
 [0.99379751]
 [0.00493372]] 

cost : 
 0.005850370983461239 

iteration ::>  573
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.00491809]
 [0.9927621 ]
 [0.99381728]
 [0.00491809]] 

cost : 
 0.005831646453628659 

iteration ::>  574
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.00490256]
 [0.99278537]
 [0.99383693]
 [0.00490256]] 

cost : 
 0.00581303553721905 

iteration ::>  575
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.00488712]
 [0.99280851]
 [0.99385647]
 [0.00488712]] 

cost : 

iteration ::>  883
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.00244041]
 [0.99645086]
 [0.99694267]
 [0.00244041]] 

cost : 
 0.0028760627661561016 

iteration ::>  884
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.00243636]
 [0.99645685]
 [0.99694777]
 [0.00243636]] 

cost : 
 0.0028712482626728777 

iteration ::>  885
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.00243231]
 [0.99646283]
 [0.99695285]
 [0.00243231]] 

cost : 
 0.0028664492654181905 

iteration ::>  886
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.00242828]
 [0.99646878]
 [0.99695792]
 [0.00242828]] 

cost : 
 0.002861665700947957 

iteration ::>  887
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.00242427]
 [0.99647471]
 [0.99696297]
 [0.00242427]] 

cost : 
 0.0028568974962756375 

iteration ::>  888
actual output :
  [[0]
 [1]
 [1]
 [0]]
prediction output :
  [[0.00242026]
 [0.99648062]
 [0.99696801]
 [0.00242026]] 

co