In [38]:
import numpy as np
from numpy.random import rand

In [39]:
x=np.array(([9,8],[6,3],[9,1],[9,8],[2,35],[4,39])) #features

In [40]:
x

array([[ 9,  8],
       [ 6,  3],
       [ 9,  1],
       [ 9,  8],
       [ 2, 35],
       [ 4, 39]])

In [41]:
y=np.array([['neural'],['positive'],['positive'],['neural'],['negative'],['negative']]) #labels

In [42]:
y

array([['neural'],
       ['positive'],
       ['positive'],
       ['neural'],
       ['negative'],
       ['negative']], dtype='<U8')

In [43]:
from sklearn.preprocessing import OneHotEncoder
enc=OneHotEncoder(sparse=False,categories='auto')
y=enc.fit_transform(y.reshape(len(y),-1))



C:\Users\sherif\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [44]:
y

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [45]:
def sigmoid(z) :
    return 1/(1+np.exp(-z))
    


In [54]:
def soft_max(z):
    return np.exp(z)/np.sum(np.exp(z) ,axis =1,keepdims=True)

In [61]:
class Neaurnetwork:
    def __init__(self,x,y,nodes_in_layer1=4,nodes_in_layer2=3,nodes_in_layer3=3,l_rate=1):
        #define x,y
        self.input_in_layer0 = x
        self.y=y
        self.l_rate=l_rate
        
        #number of neurons in layer
        self.nodes_in_layer1=nodes_in_layer1
        self.nodes_in_layer2=nodes_in_layer2
        self.nodes_in_layer3=nodes_in_layer3
        
        #set the weights (theta) metrics
        self.theta_layer0=np.random.rand(self.input_in_layer0.shape[1]+1,self.nodes_in_layer1)
        self.theta_layer1=np.random.rand(self.nodes_in_layer1+1,self.nodes_in_layer2)
        self.theta_layer2=np.random.rand(self.nodes_in_layer2+1,self.nodes_in_layer3)
  

        
    def feedforward(self):
        #compute all nodes (a1,a2,a3,a4) in layer 1
        self.z1=self.theta_layer0[0]+np.dot(self.input_in_layer0,self.theta_layer0[1:])
        self.layer1=sigmoid(self.z1)
        
         #compute all nodes (a1,a2,a3) in layer 2
        self.z2=self.theta_layer1[0]+np.dot(self.layer1,self.theta_layer1[1:])
        self.layer2=sigmoid(self.z2)
        
         #compute all nodes (a1,a2,a3) in layer 1
        self.z3=self.theta_layer2[0]+np.dot(self.layer2,self.theta_layer2[1:])
        self.layer3=soft_max(self.z3)
        
        return self.layer3
    
    ### cost function
    
    def cost_fun(self):
        self.n=self.input_in_layer0.shape[0] #number of training example
        ##self.cost=(1/self.n)*np.sum(-self.y *np.log(self.layer3)-(1-self.y)*np.log(1-self.layer3))#cross entropy
        self.cost=(1/self.n)*np.sum(-self.y*np.log(self.layer3))
        return self.cost
    
    ### back propgation
    def backpropgation(self):
        
        ## dervation of E with respect to theta and bias in layer2
        self.dE_dz3 =(1/self.n)*(self.layer3-self.y)
        
        
        
        
       
        self.dE_dtheta2=np.dot(self.layer2.T, self.dE_dz3)
        self.dbias2=np.dot(np.ones(self.n), self.dE_dz3)
        
        ## dervation of E with respect to theta and bias in layer1
        self.dE_layer2 =np.dot(self.dE_dz3,self.theta_layer2[1:].T)
        self.dE_dz2 =np.multiply(self.dE_layer2,sigmoid(self.z2)*(1-sigmoid(self.z2)))
        self.dE_dtheta1=np.dot(self.layer1.T, self.dE_dz2)
        self.dbias1=np.dot(np.ones(self.n), self.dE_dz2)
        
        
        ## dervation of E with respect to theta and bias in layer0
        self.dE_layer1 =np.dot(self.dE_dz2,self.theta_layer1[1:].T)
        self.dE_dz1 =np.multiply(self.dE_layer1,sigmoid(self.z1)*(1-sigmoid(self.z1)))
        self.dE_dtheta0=np.dot(self.input_in_layer0.T, self.dE_dz1)
        self.dbias0=np.dot(np.ones(self.n), self.dE_dz1)
        
        ## updating theta using gradient descent in layer 2,1 and 0
        self.theta_layer2[1:] = self.theta_layer2[1:]- self.l_rate * self.dE_dtheta2
        self.theta_layer1[1:] = self.theta_layer1[1:]- self.l_rate * self.dE_dtheta1
        self.theta_layer0[1:] = self.theta_layer0[1:]- self.l_rate * self.dE_dtheta0
        
        
        
        ## updating bias using gradient descent in layer 2,1 and 0
        self.theta_layer2[0] = self.theta_layer2[0] - self.l_rate * np.sum(self.dE_dz3, axis=0)
        self.theta_layer1[0] = self.theta_layer1[0] - self.l_rate * np.sum(self.dE_dz2, axis=0)
        self.theta_layer0[0] = self.theta_layer0[0] - self.l_rate * np.sum(self.dE_dz1, axis=0)
        
        
        return self
        
        
        

In [62]:

NN=Neaurnetwork(x,y)

### feed forward

In [63]:
predict=NN.feedforward()

In [64]:
print('actual output :\n ',y)

actual output :
  [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [65]:
print('prediction output :\n ',predict)

prediction output :
  [[0.18521916 0.27994732 0.53483352]
 [0.18549633 0.28001088 0.53449279]
 [0.18570734 0.28010576 0.53418691]
 [0.18521916 0.27994732 0.53483352]
 [0.18522539 0.27994385 0.53483076]
 [0.18520114 0.27994819 0.53485066]]



### back propgation

In [67]:
epochs=500

losses=[]
for i in range(epochs):
    prediction_output=NN.feedforward()
    error=NN.cost_fun()
    losses.append(error)
    u=NN.backpropgation()
    print('iteration ::> ',i+1)
    print('actual output :\n ',y)
    print('prediction output :\n ',prediction_output,'\n')
    print('cost : \n',error,'\n')
    

iteration ::>  1
actual output :
  [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
prediction output :
  [[5.09064687e-03 9.90908958e-01 4.00039501e-03]
 [3.62658762e-05 6.27280359e-03 9.93690931e-01]
 [2.93900518e-05 5.09325147e-03 9.94877358e-01]
 [5.09064687e-03 9.90908958e-01 4.00039501e-03]
 [9.93562334e-01 6.43490105e-03 2.76503549e-06]
 [9.93560535e-01 6.43669915e-03 2.76597256e-06]] 

cost : 
 0.0071081438785900175 

iteration ::>  2
actual output :
  [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
prediction output :
  [[5.08414777e-03 9.90921693e-01 3.99415886e-03]
 [3.61745139e-05 6.26359912e-03 9.93700226e-01]
 [2.93174580e-05 5.08602613e-03 9.94884656e-01]
 [5.08414777e-03 9.90921693e-01 3.99415886e-03]
 [9.93570865e-01 6.42637775e-03 2.75753178e-06]
 [9.93569068e-01 6.42817316e-03 2.75846612e-06]] 

cost : 
 0.007098215690451934 

iteration ::>  3
actual output :
  [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.

iteration ::>  362
actual output :
  [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
prediction output :
  [[3.47483832e-03 9.93987771e-01 2.53739033e-03]
 [1.71039077e-05 4.07818043e-03 9.95904716e-01]
 [1.40466281e-05 3.35539987e-03 9.96630554e-01]
 [3.47483832e-03 9.93987771e-01 2.53739033e-03]
 [9.95657880e-01 4.34087198e-03 1.24813175e-06]
 [9.95656729e-01 4.34202279e-03 1.24852929e-06]] 

cost : 
 0.004707313967388023 

iteration ::>  363
actual output :
  [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
prediction output :
  [[3.47176707e-03 9.93993459e-01 2.53477368e-03]
 [1.70742427e-05 4.07418367e-03 9.95908742e-01]
 [1.40226568e-05 3.35220489e-03 9.96633772e-01]
 [3.47176707e-03 9.93993459e-01 2.53477368e-03]
 [9.95661816e-01 4.33693861e-03 1.24587837e-06]
 [9.95660665e-01 4.33808824e-03 1.24627513e-06]] 

cost : 
 0.00470287661316059 

iteration ::>  364
actual output :
  [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0