In [32]:
import numpy as np
from numpy.random import rand

In [33]:
x=np.array(([9,8],[6,3],[9,1],[9,8])) #features

In [34]:
x

array([[9, 8],
       [6, 3],
       [9, 1],
       [9, 8]])

In [35]:
y=np.array([[0],[1],[1],[0]]) #labels

In [36]:
y

array([[0],
       [1],
       [1],
       [0]])

In [37]:
def sigmoid(z) :
    return 1/(1+np.exp(-z))
    

In [44]:
class Neaurnetwork:
    def __init__(self,x,y,nodes_in_layer1=4,nodes_in_layer2=3,nodes_in_layer3=1):
        #define x,y
        self.input_in_layer0 = x
        self.y=y
        
        #number of neurons in layer
        self.nodes_in_layer1=nodes_in_layer1
        self.nodes_in_layer2=nodes_in_layer2
        self.nodes_in_layer3=nodes_in_layer3
        
        #set the weights (theta) metrics
        self.theta_in_layer0=np.random.rand(self.input_in_layer0.shape[1]+1,self.nodes_in_layer1)
        self.theta_in_layer1=np.random.rand(self.nodes_in_layer1+1,self.nodes_in_layer2)
        self.theta_in_layer2=np.random.rand(self.nodes_in_layer2+1,self.nodes_in_layer3)
  

        
    def feedforward(self):
        #compute all nodes (a1,a2,a3,a4) in layer 1
        self.z1=self.theta_in_layer0[0]+np.dot(self.input_in_layer0,self.theta_in_layer0[1:])
        self.layer1=sigmoid(self.z1)
        
         #compute all nodes (a1,a2,a3) in layer 2
        self.z2=self.theta_in_layer1[0]+np.dot(self.layer1,self.theta_in_layer1[1:])
        self.layer2=sigmoid(self.z2)
        
         #compute all nodes (a1,a2,a3) in layer 1
        self.z3=self.theta_in_layer2[0]+np.dot(self.layer2,self.theta_in_layer2[1:])
        self.layer3=sigmoid(self.z3)
        
        return self.layer3

In [45]:

NN=Neaurnetwork(x,y)

In [46]:
predict=NN.feedforward()

In [50]:
print('actual output :\n ',y)

actual output :
  [[0]
 [1]
 [1]
 [0]]


In [51]:
print('prediction output :\n ',predict)

prediction output :
  [[0.79859302]
 [0.7978955 ]
 [0.79687214]
 [0.79859302]]
