<a href="https://colab.research.google.com/github/sherif547/NN/blob/main/nn_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
x=torch.arange(0,1,0.02).unsqueeze(dim=1)
weigt=0.7
bias=0.3
y=weigt * x + bias

In [ ]:
x[:10] ,y[:10]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

In [ ]:
len(x)

50

In [ ]:
#split data

In [ ]:
train_split=int(.8*len(x))
x_train,y_train=x[:train_split],y[:train_split]
x_test,y_test=x[train_split:],y[train_split:]

In [ ]:
train_split

40

In [ ]:

from torch import nn

## create linear reg model class
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.weights = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))
        self.bias = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.weights * x + self.bias  # Use self.bias



In [ ]:
# Create an instance of the LinearRegressionModel class
model = LinearRegressionModel()

# Access the parameters of the model
torch.manual_seed(42)
params = list(model.parameters())
print(params)

[Parameter containing:
tensor([0.4740], requires_grad=True), Parameter containing:
tensor([0.1978], requires_grad=True)]


In [ ]:
model.state_dict()

OrderedDict([('weights', tensor([0.4740])), ('bias', tensor([0.1978]))])

In [ ]:
 with torch.inference_mode():
     y_pre=model(x_test)


In [ ]:
y_pre

tensor([[0.5770],
        [0.5865],
        [0.5960],
        [0.6055],
        [0.6149],
        [0.6244],
        [0.6339],
        [0.6434],
        [0.6529],
        [0.6623]])

In [ ]:
y_test

tensor([[0.8600],
        [0.8740],
        [0.8880],
        [0.9020],
        [0.9160],
        [0.9300],
        [0.9440],
        [0.9580],
        [0.9720],
        [0.9860]])

In [ ]:
#setup loss funn
loss_fn=nn.L1Loss()
#set up optimizer
optimizer=torch.optim.SGD(params=model.parameters(),
                          lr=0.001 #learning rate = the most important hyper parm
                          )
#loss func calc the error and optimizer (gradient descent ) upgrade the parameters

In [ ]:
#loop forward propagation
epochs=1000
#loop through data
for epoch in range(epochs):
  model.train() #set all parameters and train model

  #1.forward pass
  y_pred=model(x_train)

  #calc loss fun
  loss=loss_fn(y_pred,y_train)
 # print('loss ',loss)

  #optimizer zero grad
  optimizer.zero_grad()

  #back propegation with respt parameters
  loss.backward()

  #step the optimizer (perform gradient)
  optimizer.step()


  model.eval() #turn off gradient tracking


  with torch.inference_mode():
    #do forward pass
    test_pred=model(x_test)

    #calc loss
    test_loss=loss_fn(test_pred,y_test)

   # print what happen
  if epoch %10==0:
    print('epoch: ',epoch, 'loss',loss,'test loss' ,test_loss)
    print( model.state_dict())

epoch:  0 loss tensor(0.1903, grad_fn=<MeanBackward0>) test loss tensor(0.3020)
OrderedDict([('weights', tensor([0.4744])), ('bias', tensor([0.1988]))])
epoch:  10 loss tensor(0.1788, grad_fn=<MeanBackward0>) test loss tensor(0.2885)
OrderedDict([('weights', tensor([0.4783])), ('bias', tensor([0.2088]))])
epoch:  20 loss tensor(0.1673, grad_fn=<MeanBackward0>) test loss tensor(0.2750)
OrderedDict([('weights', tensor([0.4822])), ('bias', tensor([0.2188]))])
epoch:  30 loss tensor(0.1558, grad_fn=<MeanBackward0>) test loss tensor(0.2616)
OrderedDict([('weights', tensor([0.4861])), ('bias', tensor([0.2288]))])
epoch:  40 loss tensor(0.1443, grad_fn=<MeanBackward0>) test loss tensor(0.2481)
OrderedDict([('weights', tensor([0.4900])), ('bias', tensor([0.2388]))])
epoch:  50 loss tensor(0.1327, grad_fn=<MeanBackward0>) test loss tensor(0.2346)
OrderedDict([('weights', tensor([0.4939])), ('bias', tensor([0.2488]))])
epoch:  60 loss tensor(0.1212, grad_fn=<MeanBackward0>) test loss tensor(0.22

In [ ]:
weigt,bias

(0.7, 0.3)

In [ ]:
model.state_dict()

OrderedDict([('weights', tensor([0.6884])), ('bias', tensor([0.3048]))])

In [ ]:
   y_predict=model(x_test)

In [ ]:
from IPython.utils import path
from pathlib import Path

#1.creat e a path
model_path=Path('model0')
model_path.mkdir(parents=True,exist_ok=True)

#2.create model save path
model_name='01 pytorch model.pth'
model_save_path=model_path/model_name

model_save_path

PosixPath('model0/01 pytorch model.pth')

In [ ]:
torch.save(obj=model.state_dict(),
           f=model_save_path)

In [ ]:
#to load model we shod have instance of the class
loaded_model=LinearRegressionModel()
#load save state dict
loaded_model.load_state_dict(torch.load(f=model_save_path))

<All keys matched successfully>

In [ ]:
loaded_model.state_dict()

OrderedDict([('weights', tensor([0.6884])), ('bias', tensor([0.3048]))])

In [ ]:
#make prediction
loaded_model.eval()
with torch.inference_mode():
  loaded_model_pred=loaded_model(x_test)
loaded_model_pred

tensor([[0.8556],
        [0.8694],
        [0.8831],
        [0.8969],
        [0.9107],
        [0.9244],
        [0.9382],
        [0.9520],
        [0.9657],
        [0.9795]])

In [ ]:
model(x_test)

tensor([[0.8556],
        [0.8694],
        [0.8831],
        [0.8969],
        [0.9107],
        [0.9244],
        [0.9382],
        [0.9520],
        [0.9657],
        [0.9795]], grad_fn=<AddBackward0>)

DATA

In [ ]:
device='cuda' if torch.cuda.is_available() else 'cpu'
print('using device ',device)

using device  cuda


In [ ]:
!nvidia-smi

Tue Sep 12 10:24:09 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8    10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
import torch.nn as nn

class LinearRegressionModelv2(nn.Module):
    def __init__(self):
        super().__init__()
        # Use nn.Linear to create model parameters
        self.linear_layer = nn.Linear(in_features=1, out_features=1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.linear_layer(x)

# Now you can create an instance of the model


In [ ]:
torch.manual_seed(42)
model_01=LinearRegressionModelv2()
model_01.state_dict()

OrderedDict([('linear_layer.weight', tensor([[0.7645]])),
             ('linear_layer.bias', tensor([0.8300]))])

In [ ]:
loss_fn=nn.L1Loss()

optimizer=torch.optim.SGD(params=model_01.parameters(),lr=0.01)

In [ ]:
#loop forward propagation
epochs=1000
#loop through data
for epoch in range(epochs):
  model_01.train() #set all parameters and train model

  #1.forward pass
  y_pred=model_01(x_train)

  #calc loss fun
  loss=loss_fn(y_pred,y_train)
 # print('loss ',loss)

  #optimizer zero grad
  optimizer.zero_grad()

  #back propegation with respt parameters
  loss.backward()

  #step the optimizer (perform gradient)
  optimizer.step()


  model.eval() #turn off gradient tracking


  with torch.inference_mode():
    #do forward pass
    test_pred=model(x_test)

    #calc loss
    test_loss=loss_fn(test_pred,y_test)

   # print what happen
  if epoch %10==0:
    print('epoch: ',epoch, 'loss',loss,'test loss' ,test_loss)
    print( model_01.state_dict())

epoch:  0 loss tensor(0.5552, grad_fn=<MeanBackward0>) test loss tensor(0.0054)
OrderedDict([('linear_layer.weight', tensor([[0.7606]])), ('linear_layer.bias', tensor([0.8200]))])
epoch:  10 loss tensor(0.4400, grad_fn=<MeanBackward0>) test loss tensor(0.0054)
OrderedDict([('linear_layer.weight', tensor([[0.7216]])), ('linear_layer.bias', tensor([0.7200]))])
epoch:  20 loss tensor(0.3248, grad_fn=<MeanBackward0>) test loss tensor(0.0054)
OrderedDict([('linear_layer.weight', tensor([[0.6826]])), ('linear_layer.bias', tensor([0.6200]))])
epoch:  30 loss tensor(0.2095, grad_fn=<MeanBackward0>) test loss tensor(0.0054)
OrderedDict([('linear_layer.weight', tensor([[0.6436]])), ('linear_layer.bias', tensor([0.5200]))])
epoch:  40 loss tensor(0.0943, grad_fn=<MeanBackward0>) test loss tensor(0.0054)
OrderedDict([('linear_layer.weight', tensor([[0.6046]])), ('linear_layer.bias', tensor([0.4200]))])
epoch:  50 loss tensor(0.0239, grad_fn=<MeanBackward0>) test loss tensor(0.0054)
OrderedDict([('

In [ ]:
model_01.state_dict()

OrderedDict([('linear_layer.weight', tensor([[0.6968]])),
             ('linear_layer.bias', tensor([0.3025]))])

In [ ]:
weigt,bias

(0.7, 0.3)